services:
  - type: web
    name: wolt-rocket-tracker
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_CHANNEL
        value: beforeredalert
